<?php /** @var Mage_Adminhtml_Block_Template $this */ ?>
<tr id="#{id}">
    <td>#{label}</td>
    <td>
        <div class="main-row">
            <label for="#{id}-#{code}-default" ><?php echo $this->__('Default');?><span class="required">*</span></label><input id="#{id}-#{code}-default" name="#{fieldPrefix}[#{code}][slug]" type="text" class="required-entry default-slug" />
        </div>
        <div class="locale-template" style="display: none;">
            <label class="label"><span class="text"></span><span class="required">*</span></label><input type="text" class="input" />
            <button class="delete scalable" type="button"><span><span><span><?php echo $this->__('Delete');?></span></span></span></button>
        </div>
        <div class="locale-container"></div>
        <div>
            <select id="#{id}-#{code}-locale" class="locale-select" data-input-name="#{fieldPrefix}[#{code}][store_slug][__locale__]" data-input-id="#{id}-#{code}-__locale__"></select>
            <button class="scalable add" type="button">
                <span><span><span><?php echo $this->__('Add');?></span></span></span>
            </button>
        </div>
    </td>
    <td><button class="delete delete-row scalable" type="button"><span><span><span><?php echo $this->__('Delete');?></span></span></span></button></td>
</tr>
